version: "3.9"

services:

  backend:
    image: fredogado/backend:latest
    environment:
      DATABASE_URL: postgresql://bd_user:password123@postgres:5432/bd_manchot
      REDIS_HOST: redis-cache
      REDIS_PORT: 6379
    networks:
      - backend-net
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]

  frontend:
    image: fredogado/frontend:latest
    ports:
      - "3000:80"
    networks:
      - frontend-net
      - backend-net
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      environment:
        BACKEND_HOST: backend
        #- VITE_API_URL=http://backend:8000

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: bd_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bd_manchot
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bd_user -d bd_manchot"]

  redis-cache:
    image: redis:alpine
    networks:
      - backend-net
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

volumes:
  pgdata:

networks:
  frontend-net:
    driver: overlay
  backend-net:
    driver: overlay
